const {chromium}=require('C:/Users/mail/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.route('**/api/health',r=>r.fulfill({json:{omr:false}}));
 await page.goto('http://127.0.0.1:5173/');await page.waitForFunction(()=>document.getElementById('service-state').textContent.includes('缺少 Audiveris'));
 assert.equal(await page.locator('#start-button').isDisabled(),true);await page.locator('#sample-button').click();assert.equal(await page.locator('.note-event').count(),16);assert.equal(await page.locator('#start-button').isEnabled(),true);assert.equal(await page.locator('#accuracy').innerText(),'—');await page.screenshot({path:'outputs/desktop.png',fullPage:true});
 await page.locator('#demo-button').click();await page.waitForFunction(()=>document.getElementById('progress-label').textContent==='100%',null,{timeout:18000});assert.ok(Number(await page.locator('#accuracy').innerText())<100);assert.equal(await page.locator('#export-button').isEnabled(),true);assert.match(await page.locator('#notice').innerText(),/模拟/);await page.locator('#reset-button').click();assert.equal(await page.locator('#accuracy').innerText(),'—');
 const parsed=await page.evaluate(async()=>{const {parseMusicXML}=await import('/score.js');const xml='<score-partwise><part id="P1"><measure number="1"><attributes><divisions>2</divisions></attributes><note><pitch><step>C</step><octave>4</octave></pitch><duration>2</duration></note><note><chord/><pitch><step>E</step><octave>4</octave></pitch><duration>2</duration></note><note><rest/><duration>2</duration></note><note><pitch><step>D</step><alter>1</alter><octave>4</octave></pitch><duration>2</duration></note></measure></part></score-partwise>';return parseMusicXML(xml);});assert.deepEqual(parsed.events.map(e=>e.pitches),[[60,64],[63]]);assert.deepEqual(parsed.events.map(e=>e.beat),[0,2]);
 await page.locator('#pdf-input').setInputFiles({name:'not-pdf.pdf',mimeType:'application/pdf',buffer:Buffer.from('invalid')});await page.waitForFunction(()=>document.getElementById('notice').textContent.includes('不是有效'));
 await page.locator('#pdf-input').setInputFiles('outputs/test-score.pdf');await page.waitForFunction(()=>document.querySelectorAll('#pdf-pages canvas').length===1);await page.waitForFunction(()=>document.getElementById('notice').textContent.includes('缺少 Audiveris'));assert.equal(await page.locator('#notice').getAttribute('class'),'notice warning');assert.equal(await page.locator('#start-button').isDisabled(),true);await page.screenshot({path:'outputs/pdf.png',fullPage:true});
 await page.locator('#sample-button').click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'outputs/mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);console.log('Browser checks passed: score parsing, demo, reset, invalid PDF, real PDF preview, mobile layout.');await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1});
