const {chromium}=require('C:/Users/mail/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,channel:'msedge',args:['--autoplay-policy=no-user-gesture-required']});try{
 const p=await b.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5173/');
 await p.locator('#sample-button').click();await p.locator('[data-index="8"]').click();await p.waitForFunction(()=>document.querySelector('#play-button').textContent.includes('暂停'));assert.ok(parseInt(await p.locator('#progress-label').textContent())>=50);
 await p.locator('#play-button').click();await p.locator('#autoplay').uncheck();await p.locator('#xml-input').setInputFiles('tests/playback.musicxml');await p.locator('.engraved-sheet [data-index="2"]').first().waitFor();await p.locator('.engraved-sheet [data-index="2"]').first().press('Enter');await p.waitForFunction(()=>document.querySelector('#play-button').textContent.includes('暂停'));assert.ok(parseInt(await p.locator('#progress-label').textContent())>=62);
 await p.locator('#play-button').click();await p.screenshot({path:'outputs/refined-score.png',fullPage:true});
 const result=await p.evaluate(async()=>{const {ScorePlayer}=await import('/player.js');const player=new ScorePlayer();player.load({events:[{beat:0,notes:[{midi:60,duration:8}]}]});player.seek(0);await player.play();const voice=[...player.voices][0];const sampled=voice.oscillator instanceof AudioBufferSourceNode;const count=player.samples.length;player.stop();await player.context.close();return {sampled,count};});assert.equal(result.sampled,true);assert.equal(result.count,5);assert.deepEqual(errors,[]);console.log('PASS: sample click seek, engraved keyboard seek, five velocity layers, sampled audio playback');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
